
#pragma once 

// HARDWARE
#define NUM_LEDS  110
#define NUM_BUTTONS 4
#define LEDS_PIN    5
#define BUTTON1_PIN 27
#define BUTTON2_PIN 13
#define BUTTON3_PIN 14
#define BUTTON4_PIN 15
#define STARTUP_DELAY 3000

// NETWORKING
#define NETWORK_SSID "Vodafone-CA1C4A"
#define NETWORK_PASSWORD "eR5nn3NkRx"
#define NETWORK_NUM_ATTEMPTS 10
#define NETWORK_TIME_BETWEEN_ATTEMPTS 2500

// TTIME
#define TIME_GMT_OFFSET 3600
#define TIME_DAYLIGHT_OFFSET 3600
#define TIME_NTP_SERVER "pool.ntp.org"

// GRAPHICS
#define FRAME_RATE 60