
#pragma once 

// HARDWARE
#define NUM_LEDS  110
#define NUM_BUTTONS 4
#define LEDS_PIN    5
#define BUTTON1_PIN 27
#define BUTTON2_PIN 14
#define BUTTON3_PIN 12
#define BUTTON4_PIN 13
#define DEBOUNCE_INTERVAL 25
#define STARTUP_DELAY 3000

// NETWORKING
#define NETWORK_SSID "Vodafone-CA1C4A"
#define NETWORK_PASSWORD "eR5nn3NkRx"
#define NETWORK_NUM_ATTEMPTS_PER_CYCLE 3
#define NETWORK_NUM_CYCLES 4
#define NETWORK_TIME_BETWEEN_ATTEMPTS 2500

// TTIME
#define TIME_GMT_OFFSET 3600
#define TIME_DAYLIGHT_OFFSET 3600
#define TIME_NTP_SERVER "pool.ntp.org"

// GRAPHICS
#define FRAME_RATE 60

// WORDS

#define LETTER_HEIGHT 4
#define LETTER_WIDTH 3
#define LETTER_SPACING 1

// EEPROM
#define EEPROM_SIZE 64
#define EEPROM_ADDRESS_COLOR_R 0
#define EEPROM_ADDRESS_COLOR_G 1
#define EEPROM_ADDRESS_COLOR_B 2
#define EEPROM_ADDRESS_BRIGTHNESS 3