
#pragma once 

// SCREEN
#define NUM_LEDS  110
#define SCREEN_WIDTH 11
#define SCREEN_HEIGHT 10

// HARDWARE
#define NUM_BUTTONS 4
#define LEDS_PIN    5
#define BUTTON1_PIN 27
#define BUTTON2_PIN 14
#define BUTTON3_PIN 12
#define BUTTON4_PIN 13
#define DEBOUNCE_INTERVAL 25
#define STARTUP_DELAY 3000

// NETWORKING
#define NETWORK_SSID "WordClock"
#define NETWORK_PASSWORD "SetTimeNow"
#define NETWORK_NUM_ATTEMPTS_PER_CYCLE 3
#define NETWORK_NUM_CYCLES 4
#define NETWORK_TIME_BETWEEN_ATTEMPTS 2500

// TIME
#define TIME_GMT_OFFSET 3600
#define TIME_DAYLIGHT_OFFSET 3600
#define TIME_NTP_SERVER "pool.ntp.org"

// GRAPHICS
#define FRAME_RATE 60
#define BRIGHTNESS_INCREMENT 6

// WORDS
#define LETTER_HEIGHT 4
#define LETTER_WIDTH 3
#define LETTER_SPACING 1

// EEPROM
#define EEPROM_SIZE 10
#define EEPROM_ADDRESS_COLOR_R 1
#define EEPROM_ADDRESS_COLOR_G 2
#define EEPROM_ADDRESS_COLOR_B 3
#define EEPROM_ADDRESS_BRIGTHNESS 4